### ISSUE TITLE
Issue with sending BTC in smaller amounts

### ISSUE THREAD

**Issue by jdogresorg** [loon3/XCP-Wallet-for-Chrome#1]
When sending smaller amounts of BTC the amount sent is off by 1 satoshi.

I created an invoice which asked me to pay 0.0024. I entered 0.0024 into the wallet plugin and clicked send, but the transaction shows 0.00239999 

I am able to reproduce this behavior.

Screenshot showing invoice for 0.0024 BTC
http://gyazo.com/b6e0d844749adf9ba56e1a714a7ffe14

Screenshot showing I am entering 0.0024 BTC as payment amount
http://gyazo.com/699ba7459a15387bca0a481b49e371ef

Screenshot showing that I paid 0.024 BTC via wallet... but invoice shows underpaid by 1 satoshi
http://gyazo.com/b8e8d45a808f462231cc01d44a7a3cb1

Transaction showing that invoice was underpaid 1 satoshi... and miner was overpaid 1 satoshi
https://chain.so/tx/BTC/2ab6cb51cf1f3369758b4e55a9194f5ed6bd32d927dfb0bd11c5e0445a3534e8

**Comment by loon3** [comment]
I was able to reproduce as well using the same send amount, https://blockchain.info/tx/337440b3e8a49c1edf4107357a34cd9562820cc10572ab3b79dedcba5b7fe6a7  

This is likely a floating point math error.  Should have a fix shortly...

**Comment by loon3** [comment]
Fixed with latest release v0.1.2, should update in Chrome Web Store in the next hour or so
